app = ''
primary_region = 'ord'

[build]

[deploy]

[[mounts]]
  source = 'models'
  destination = '/app/models'
  initial_size = '200gb'

[http_service]
  internal_port = 8188
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-8x'
  memory = '16gb'
  gpu_kind = 'l40s'
  cpu_kind = 'performance'
  cpus = 8
